name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ "/app/src/main/res/values-*/strings.xml" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifact debug APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: mset9installer-artifact-debug.apk
        path: app/build/outputs/apk/artifact/debug/app-artifact-debug.apk
        
    - name: Upload artifact unsigned release APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: mset9installer-artifact-release-unsigned.apk
        path: app/build/outputs/apk/artifact/release/app-artifact-release-unsigned.apk

    - name: Decode keystore
      uses: timheuer/base64-to-file@v1
      id: android_keystore
      with:
        fileName: "android_keystore.keystore"
        encodedString: ${{ secrets.KEYSTORE }}
    - name: Assemble artifact signed release APK
      run: ./gradlew assembleArtifactRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.APP_NAME_KEY }} -Pandroid.injected.signing.key.password=${{ secrets.APP_NAME_KEY_PASSWORD }}

    - name: Upload artifact signed release APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: mset9installer-artifact-release.apk
        path: app/build/outputs/apk/release/app-artifact-release.apk
